name: Generate and Deploy Javadoc

on:
  push:
    branches:
      - master  # Adjust the branch as per your needs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      
    - name: Generate Javadoc
      run: mvn javadoc:javadoc
      working-directory: ./

    - name: Publish Javadoc
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/docs/javadoc
